<?php

/******* Welcome page *******/

define('_jumbo_title', 'Welkom bij Speel Direkt!');
define('_jumbo_text', 'Hier zal je PlayDirekt leren kennen door het spelen van een aantal microgames.');
define('_panel1_title', 'Game 1');
define('_panel2_title', 'Game 2');
define('_panel3_title', 'Game 3');
define('_panel1_text', 'Hier komt de uitleg voor game 1');
define('_panel2_text', 'Hier komt de uitleg voor game 2');
define('_panel3_text', 'Hier komt de uitleg voor game 3');